[package]
name = "greenie"
version = "0.1.1"
authors = ["playXE <adel.prokurov@protonmail.com>"]
edition = "2018"
repository = "https://github.com/playXE/greenie"
readme = "README.md"
keywords = ["perceptron","neural-network","network","nerual","genetic"]
license = "MIT"
description = "Green threads & generators"
[dependencies]
greenie-proc = "0.1"